version: "3.7"

services:

  api_service:
    image: "openjdk:17-jdk-oraclelinux8"
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    working_dir: .
    ports:
      - 8080:8080
    depends_on:
      - postgres_db

  postgres_db:
    image: "postgres:latest"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: root